name: api-docs

on:
  push:

jobs:
  api-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with: { node-version: 18 }

      - id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: validate swagger
        run: |
          npm -i
          npm test

      - name: deploy
        if: ${{ github.ref_name == "master" || github.ref_name == "main" }}
        run: |
          export GH_TOKEN=$GITHUB_TOKEN
          npm run gh-pages
